"""Cross-port compatibility — the wire format is shared with tasqr-mcp-node.

The node fixture was generated by the Node client with a fixed test DEK; every
case must decrypt here byte-for-byte, or the two ports have silently diverged
(a task encrypted on one machine would be unreadable on a teammate's). The
python fixture is decrypted by the Node suite for the reverse direction.
Regenerate the fixtures from their generating repos if the format legitimately
changes — never hand-edit them.
"""

import base64
import json
import pathlib

import pytest

FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def _load(name):
    return json.loads((FIXTURES / name).read_text())


def _crypto(fixture):
    from tasqr_mcp.crypto import ClientCrypto

    return ClientCrypto(dek=base64.b64decode(fixture["dek_b64"]), org_id=fixture["org_id"])


@pytest.mark.parametrize("name", ["cross_port_node.json", "cross_port_python.json"])
def test_fixture_blobs_decrypt(name):
    fixture = _load(name)
    c = _crypto(fixture)
    for case in fixture["cases"]:
        got = c._decrypt_str(case["marker"], case["task_id"], case["field"])
        assert got == case["plaintext"], f"case {case['field']}@{case['task_id']} in {name}"


def test_node_fixture_blob_refuses_wrong_slot():
    from tasqr_mcp.crypto import ClientCryptoError

    fixture = _load("cross_port_node.json")
    c = _crypto(fixture)
    case = fixture["cases"][0]
    with pytest.raises(ClientCryptoError, match="moved|tampered"):
        c._decrypt_str(case["marker"], case["task_id"], "output")
